export const HTMLTagsConstants = {
	CLOSE_SECTION: "</section>",
	CLOSE_DIV: "</div>",
	CLOSE_H1: "</h1>",
	CLOSE_H2: "</h2>",
	CLOSE_H3: "</h3>",
	CLOSE_H4: "</h4>",
	CLOSE_H5: "</h5>",
	CLOSE_H6: "</h6>",
	CLOSE_SPAN: "</span>",
	CLOSE_FORM: "</form>",
	CLOSE_LABEL: "</label>",
	CLOSE_INPUT: "</input>",
	CLOSE_TEXTAREA: "</textarea>",
};

export const HTMLAttributesConstants = {
	ROOT: "root",
	STAGE: "stage",
	TOPBAR: "topbar",
	TOP_TITLE: "top-title",
	CONTAINER: "container",
	SECTION_CONTAINER: "section-container",
	LIST_CONTAINER: "list-container",
	LIST_INNER_CONTAINER: "list-inner-container",
	LIST_BUTTON: "list-button",
	BUTTON: "button",
	LIST_ADD_BUTTON: "list-add-button",
	NO_ITEMS_IN_LIST_MESSAGE: "no-items-in-list-message",
};

export const HTMLSubjectAttributesConstants = {
	SUBJECT: "subject",
	SUBJECT_CONTAINER: `subject-${HTMLAttributesConstants.CONTAINER}`,
	SUBJECT_BUTTON: `subject-${HTMLAttributesConstants.BUTTON}`,
	ADD_SUBJECT: "add-subject",
	ADD_SUBJECT_BUTTON: `add-subject-${HTMLAttributesConstants.BUTTON}`,
	ADD_SUBJECT_BUTTON_TEXT: "Add Subject",
	NO_SUBJECTS_MESSAGE_ID: "no-subjects-in-list-message",
	NO_SUBJECTS_MESSAGE: "No Subjects Added Yet",
	ADD_SUBJECT_MODAL_TITLE: "Add New Subject",
	ADD_SUBJECT_MODAL_DESCRIPTION:
		"Placeholder description for adding a new subject. Please fill in the required fields and any additional information as needed.",
	ADD_SUBJECT_MODAL_SUBJECT_NAME_FIELD: "subject-name",
	ADD_SUBJECT_MODAL_SUBJECT_NAME_FIELD_LABEL: "Subject Name",
	ADD_SUBJECT_MODAL_SUBJECT_NAME_FIELD_PLACEHOLDER:
		"Enter name of the subject",
	ADD_SUBJECT_MODAL_SUBJECT_CODE_FIELD: "subject-code",
	ADD_SUBJECT_MODAL_SUBJECT_CODE_FIELD_LABEL: "Subject Code",
	ADD_SUBJECT_MODAL_SUBJECT_CODE_FIELD_PLACEHOLDER: "Enter subject code",
	ADD_SUBJECT_MODAL_SUBJECT_DESCRIPTION_FIELD: "subject-description",
	ADD_SUBJECT_MODAL_SUBJECT_DESCRIPTION_FIELD_LABEL: "Subject Description",
	ADD_SUBJECT_MODAL_SUBJECT_DESCRIPTION_FIELD_PLACEHOLDER:
		"Enter subject description",
};

export const HTMLFieldAttributesConstants = {
	FIELD: "field",
	INPUT: "input",
	LABEL: "label",
	ADD: "add",
	CLOSE: "close",
	FORM: "form",
	TEXT: "text",
	TEXTAREA: "textarea",
	DEFAULT: "default",
	SYSTEM_DEFAULT: "system-default",
}

export const HTMLModalAttributesConstants = {
	MODAL: "modal",
	MODAL_CONTAINER: "modal-container",
	MODAL_TITLEBAR: "modal-titlebar",
	MODAL_TITLE: "modal-title",
	MODAL_CLOSE_BUTTON: "modal-close-button",
	MODAL_CONTENT: "modal-content",
	MODAL_DESCRIPTION: "modal-description",
	MODAL_FORM: "modal-form",
	MODAL_ADD_BUTTON: "modal-add-button",
	MODAL_FIELD: "modal-field",
	MODAL_FIELD_LABEL: "modal-field-label",
	MODAL_FIELD_TEXT_TEXTAREA: "modal-field-text-textarea",
	MODAL_SUBMIT_BUTTON_TEXT: "Add &#x2b;",
	FIELD: "field",
	INPUT: "input",
	LABEL: "label",
	CLOSE: "close",
};

export const HTMLPopupAttributesConstants = {
	POPUP: "popup",
	POPUP_CONTAINER: "popup-container",
	POPUP_TITLEBAR: "popup-titlebar",
	POPUP_TITLE: "popup-title",
	POPUP_DESCRIPTION: "popup-description",
	CLOSE: "close",
	CLOSE_TEXT: "Close",
	POPUP_CLOSE_BUTTON: "popup-close-button",
	ALERT: "alert",
	ALERT_TEXT: "Alert",
	INFO: "info",
	INFO_TEXT: "&#9432; Info",
	WARNING: "warning",
	WARNING_TEXT: "&#9888; Warning",
	ERROR: "error",
	ERROR_TEXT: "&#8252; Error",
	SUCCESS: "success",
	SUCCESS_TEXT: "&#9989; Success",
};
